(global-set-key (kbd "H-i") (lambda() (interactive)(find-file "~/.emacs.d/init.el")))
(global-set-key (kbd "H-s") 'save-buffer)
(global-set-key (kbd "H-z") 'zsh)
(global-set-key (kbd "H-h") 'eshell)
(global-set-key (kbd "H-j")
		(lambda ()
		  (interactive)
		  (if (string-equal (message "%s" major-mode) "eshell-mode")
		      (funcall 'eshell/clear))
		  (if (string-equal (message "%s" major-mode) "slime-repl-mode")
		      (funcall 'slime-repl-clear-buffer))
		  (if (string-equal (message "%s" major-mode) "cider-mode")
		      (funcall 'cider-repl-clear-buffer))))
(global-set-key (kbd "H-k") 'kill-buffer)
(global-set-key (kbd "H-x") 'kill-region)
(global-set-key (kbd "H-c") 'kill-ring-save)
(global-set-key (kbd "H-v") 'yank)
(global-set-key (kbd "H-e") 'sudo-edit)
(global-set-key (kbd "H-q") 'split-window-horizontally)
(global-set-key (kbd "H-w") 'split-window-vertically)
(global-set-key (kbd "H-a") 'balance-windows)
(global-set-key (kbd "H-b") 'buffer-menu)
(global-set-key (kbd "H-=") 'text-scale-increase)
(global-set-key (kbd "H--") 'text-scale-decrease)
(global-set-key (kbd "H-o") 'other-window)
(global-set-key (kbd "H-p") 'previous-multiframe-window)
(global-set-key (kbd "H-f") 'maximize-window)
(global-set-key (kbd "H-l") 'ispell)
